#!/bin/bash
# ProveIT Build Script
# Scans assets, updates service worker cache list, and bumps version numbers

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      ProveIT Build Script v1.0         ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# ============================================
# 1. Get current version and increment
# ============================================
echo -e "${YELLOW}[1/4] Detecting current version...${NC}"

# Extract current version from index.html (macOS compatible)
CURRENT_VERSION=$(grep -o 'presentation\.css?v=[0-9]*' index.html | head -1 | sed 's/.*v=//')
if [ -z "$CURRENT_VERSION" ]; then
    CURRENT_VERSION=1
fi

NEW_VERSION=$((CURRENT_VERSION + 1))
echo -e "       Current version: ${RED}v${CURRENT_VERSION}${NC}"
echo -e "       New version:     ${GREEN}v${NEW_VERSION}${NC}"

# ============================================
# 2. Scan assets directory
# ============================================
echo ""
echo -e "${YELLOW}[2/4] Scanning assets...${NC}"

# Arrays to hold assets
IMAGES=()
VIDEOS=()
AUDIO=()

# Scan images
while IFS= read -r -d '' file; do
    # Convert to relative path
    rel_path="${file#$SCRIPT_DIR}"
    IMAGES+=("$rel_path")
done < <(find "$SCRIPT_DIR/assets/images" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.gif" -o -iname "*.svg" -o -iname "*.webp" \) -print0 2>/dev/null || true)

# Scan videos
while IFS= read -r -d '' file; do
    rel_path="${file#$SCRIPT_DIR}"
    VIDEOS+=("$rel_path")
done < <(find "$SCRIPT_DIR/assets/video" -type f \( -iname "*.mp4" -o -iname "*.webm" -o -iname "*.mov" \) -print0 2>/dev/null || true)

# Scan audio (check both assets/audio and assets/video for mp3)
while IFS= read -r -d '' file; do
    rel_path="${file#$SCRIPT_DIR}"
    AUDIO+=("$rel_path")
done < <(find "$SCRIPT_DIR/assets" -type f \( -iname "*.mp3" -o -iname "*.wav" -o -iname "*.ogg" \) -print0 2>/dev/null || true)

echo -e "       Images: ${GREEN}${#IMAGES[@]}${NC}"
echo -e "       Videos: ${GREEN}${#VIDEOS[@]}${NC}"
echo -e "       Audio:  ${GREEN}${#AUDIO[@]}${NC}"
TOTAL=$((${#IMAGES[@]} + ${#VIDEOS[@]} + ${#AUDIO[@]}))
echo -e "       Total:  ${GREEN}${TOTAL}${NC} assets"

# ============================================
# 3. Generate new sw.js
# ============================================
echo ""
echo -e "${YELLOW}[3/4] Updating service worker...${NC}"

cat > sw.js << 'SWHEADER'
// ProveIT Service Worker - Offline Support
// Auto-generated by build.sh
SWHEADER

echo "// Version: ${NEW_VERSION}" >> sw.js
echo "" >> sw.js

cat >> sw.js << SWCACHE
const CACHE_NAME = 'proveit-v${NEW_VERSION}';

// Assets to cache on install
const ASSETS_TO_CACHE = [
    '/',
    '/index.html',
    '/css/presentation.css',
    '/js/preloader.js',
    '/js/slide-config.js',
    '/js/presentation.js',

SWCACHE

# Add images
echo "    // Images (${#IMAGES[@]} files)" >> sw.js
for img in "${IMAGES[@]}"; do
    echo "    '${img}'," >> sw.js
done
echo "" >> sw.js

# Add videos
echo "    // Videos (${#VIDEOS[@]} files)" >> sw.js
for vid in "${VIDEOS[@]}"; do
    echo "    '${vid}'," >> sw.js
done
echo "" >> sw.js

# Add audio
if [ ${#AUDIO[@]} -gt 0 ]; then
    echo "    // Audio (${#AUDIO[@]} files)" >> sw.js
    for aud in "${AUDIO[@]}"; do
        echo "    '${aud}'," >> sw.js
    done
    echo "" >> sw.js
fi

# Close the array and add the rest of the service worker code
cat >> sw.js << 'SWFOOTER'
];

// Install event - cache all assets
self.addEventListener('install', (event) => {
    console.log('[SW] Installing service worker...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => {
                console.log('[SW] Caching assets...');
                // Cache assets one by one to handle failures gracefully
                return Promise.allSettled(
                    ASSETS_TO_CACHE.map(url =>
                        cache.add(url).catch(err => {
                            console.warn(`[SW] Failed to cache: ${url}`, err);
                        })
                    )
                );
            })
            .then(() => {
                console.log('[SW] All assets cached');
                return self.skipWaiting();
            })
    );
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
    console.log('[SW] Activating service worker...');
    event.waitUntil(
        caches.keys()
            .then((cacheNames) => {
                return Promise.all(
                    cacheNames
                        .filter((name) => name !== CACHE_NAME)
                        .map((name) => {
                            console.log(`[SW] Deleting old cache: ${name}`);
                            return caches.delete(name);
                        })
                );
            })
            .then(() => self.clients.claim())
    );
});

// Fetch event - serve from cache, fallback to network
self.addEventListener('fetch', (event) => {
    // Skip non-GET requests
    if (event.request.method !== 'GET') return;

    // Skip external requests (fonts, etc.)
    if (!event.request.url.startsWith(self.location.origin)) {
        return;
    }

    event.respondWith(
        caches.match(event.request)
            .then((cachedResponse) => {
                if (cachedResponse) {
                    // Return cached version
                    return cachedResponse;
                }

                // Not in cache, fetch from network
                return fetch(event.request)
                    .then((networkResponse) => {
                        // Cache the new response for future
                        if (networkResponse.ok) {
                            const responseClone = networkResponse.clone();
                            caches.open(CACHE_NAME)
                                .then((cache) => {
                                    cache.put(event.request, responseClone);
                                });
                        }
                        return networkResponse;
                    })
                    .catch(() => {
                        // Network failed, return offline fallback if available
                        console.log('[SW] Network failed for:', event.request.url);
                    });
            })
    );
});

// Message event - handle commands from main thread
self.addEventListener('message', (event) => {
    if (event.data === 'skipWaiting') {
        self.skipWaiting();
    }
});
SWFOOTER

echo -e "       ${GREEN}✓${NC} sw.js updated with ${TOTAL} assets"

# ============================================
# 4. Update version numbers in index.html
# ============================================
echo ""
echo -e "${YELLOW}[4/4] Updating cache-busting versions...${NC}"

# Update CSS version
sed -i.bak "s/presentation\.css?v=[0-9]*/presentation.css?v=${NEW_VERSION}/g" index.html

# Update JS versions
sed -i.bak "s/preloader\.js?v=[0-9]*/preloader.js?v=${NEW_VERSION}/g" index.html
sed -i.bak "s/slide-config\.js?v=[0-9]*/slide-config.js?v=${NEW_VERSION}/g" index.html
sed -i.bak "s/presentation\.js?v=[0-9]*/presentation.js?v=${NEW_VERSION}/g" index.html

# Remove backup files
rm -f index.html.bak

echo -e "       ${GREEN}✓${NC} index.html updated to v${NEW_VERSION}"

# ============================================
# Summary
# ============================================
echo ""
echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║           Build Complete!              ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Version:  ${BLUE}v${NEW_VERSION}${NC}"
echo -e "  Assets:   ${BLUE}${TOTAL}${NC} files cached"
echo ""
echo -e "  ${YELLOW}Files updated:${NC}"
echo -e "    - sw.js"
echo -e "    - index.html"
echo ""
echo -e "  ${YELLOW}Next steps:${NC}"
echo -e "    1. Test locally: ${BLUE}python3 -m http.server 8000${NC}"
echo -e "    2. Commit changes: ${BLUE}git add -A && git commit -m 'Build v${NEW_VERSION}'${NC}"
echo -e "    3. Deploy to production"
echo ""
