// ProveIT Service Worker - Offline Support
// Auto-generated by build.sh
// Version: 34

const CACHE_NAME = 'proveit-v34';

// Assets to cache on install
const ASSETS_TO_CACHE = [
    '/',
    '/index.html',
    '/css/presentation.css',
    '/js/preloader.js',
    '/js/slide-config.js',
    '/js/presentation.js',

    // Images (66 files)
    '/assets/images/john-dyck.png',
    '/assets/images/i3Xscreen.png',
    '/assets/images/HighByte_White.png',
    '/assets/images/Matthew.png',
    '/assets/images/cesmiiProveIt.png',
    '/assets/images/Picture_53.png',
    '/assets/images/Anthony.png',
    '/assets/images/mthree-logo.png',
    '/assets/images/computerMonitor.png',
    '/assets/images/aron-semle.png',
    '/assets/images/MrRogers_LR.jpg',
    '/assets/images/arrowRight.png',
    '/assets/images/Picture_Placeholder_31.png',
    '/assets/images/caleb-eastman.png',
    '/assets/images/graeme-welton.png',
    '/assets/images/i3X_circle.png',
    '/assets/images/FlowSoftware_White.png',
    '/assets/images/fredImage.png',
    '/assets/images/flagBackground.jpg',
    '/assets/images/cesmii-logo-white.png',
    '/assets/images/seussBook.png',
    '/assets/images/slide44-graphic-36.png',
    '/assets/images/slide44-graphic-35.png',
    '/assets/images/XPGrass.jpg',
    '/assets/images/GP_1.png',
    '/assets/images/interoperabilitybridge.png',
    '/assets/images/GP_2.png',
    '/assets/images/cesmiiDarkerOverlay.png',
    '/assets/images/scott-robertson.png',
    '/assets/images/SMImperative1_NEW.svg',
    '/assets/images/slide44-graphic-27.png',
    '/assets/images/msWindows31.png',
    '/assets/images/travis-cox.png',
    '/assets/images/AWS_White.png',
    '/assets/images/WorkingGroup.png',
    '/assets/images/GP_Summary.png',
    '/assets/images/slide44-graphic-28.png',
    '/assets/images/InductiveAutomation_White.png',
    '/assets/images/arrowUp.png',
    '/assets/images/Laptop.png',
    '/assets/images/CTA1.png',
    '/assets/images/page8-9.png',
    '/assets/images/slide47-picture-21.png',
    '/assets/images/No_Graphic.png',
    '/assets/images/jonathan-wise.png',
    '/assets/images/CTA3.png',
    '/assets/images/CTA2.png',
    '/assets/images/NameKey_HalfCircle.png',
    '/assets/images/page6.png',
    '/assets/images/Wonderware.png',
    '/assets/images/Picture_4.png',
    '/assets/images/cesmii-logo.png',
    '/assets/images/GeorgiaPacific_Logo.png',
    '/assets/images/page7.png',
    '/assets/images/page5.png',
    '/assets/images/page4.png',
    '/assets/images/Picture_63.png',
    '/assets/images/Siemens_White.png',
    '/assets/images/SMImperative2.png',
    '/assets/images/page1.png',
    '/assets/images/page3.png',
    '/assets/images/page11.png',
    '/assets/images/craig-egan.png',
    '/assets/images/cesmii-logo-full.png',
    '/assets/images/page10.png',
    '/assets/images/page2.png',

    // Videos (8 files)
    '/assets/video/energy_sphere.mp4',
    '/assets/video/whispylinesbg_c_slower_darker.mp4',
    '/assets/video/simpsonsVideo2.mp4',
    '/assets/video/whispylinesbg_b_slower_darker.mp4',
    '/assets/video/introductionToInTouchCropped.mp4',
    '/assets/video/background.mp4',
    '/assets/video/i3xBackground.mp4',
    '/assets/video/whispylinesbg_d_slower_alt_colors_5.mp4',

    // Audio (1 files)
    '/assets/video/misterRogersThemeAudio.mp3',

];

// Install event - cache all assets
self.addEventListener('install', (event) => {
    console.log('[SW] Installing service worker...');
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => {
                console.log('[SW] Caching assets...');
                // Cache assets one by one to handle failures gracefully
                return Promise.allSettled(
                    ASSETS_TO_CACHE.map(url =>
                        cache.add(url).catch(err => {
                            console.warn(`[SW] Failed to cache: ${url}`, err);
                        })
                    )
                );
            })
            .then(() => {
                console.log('[SW] All assets cached');
                return self.skipWaiting();
            })
    );
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
    console.log('[SW] Activating service worker...');
    event.waitUntil(
        caches.keys()
            .then((cacheNames) => {
                return Promise.all(
                    cacheNames
                        .filter((name) => name !== CACHE_NAME)
                        .map((name) => {
                            console.log(`[SW] Deleting old cache: ${name}`);
                            return caches.delete(name);
                        })
                );
            })
            .then(() => self.clients.claim())
    );
});

// Fetch event - serve from cache, fallback to network
self.addEventListener('fetch', (event) => {
    // Skip non-GET requests
    if (event.request.method !== 'GET') return;

    // Skip external requests (fonts, etc.)
    if (!event.request.url.startsWith(self.location.origin)) {
        return;
    }

    event.respondWith(
        caches.match(event.request)
            .then((cachedResponse) => {
                if (cachedResponse) {
                    // Return cached version
                    return cachedResponse;
                }

                // Not in cache, fetch from network
                return fetch(event.request)
                    .then((networkResponse) => {
                        // Cache the new response for future
                        if (networkResponse.ok) {
                            const responseClone = networkResponse.clone();
                            caches.open(CACHE_NAME)
                                .then((cache) => {
                                    cache.put(event.request, responseClone);
                                });
                        }
                        return networkResponse;
                    })
                    .catch(() => {
                        // Network failed, return offline fallback if available
                        console.log('[SW] Network failed for:', event.request.url);
                    });
            })
    );
});

// Message event - handle commands from main thread
self.addEventListener('message', (event) => {
    if (event.data === 'skipWaiting') {
        self.skipWaiting();
    }
});
